# Generated by Django 2.2.8 on 2021-12-19 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('service_name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=250)),
                ('date_created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
