# Generated by Django 2.2.8 on 2021-12-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211220_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='service_name',
            field=models.CharField(choices=[('WD', 'Website development'), ('DM', 'Digital Marketing'), ('SD', 'Systems Development')], max_length=2),
        ),
    ]
